openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This documentation is for the Contacts Book app
tags:
  - name: Contacts
    description: The operations for working with Contacts
  - name: Auth
    description: The operations for working with Authentication
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-pavk.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
